eureka:
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/employee/**  
  config:
    import: optional:configserver:http://localhost:8084      
server:
  port: '8083'
  
spring-cloud-gateway:
  value: 'Gateway Local Environment'
